version: "3.4"

services:
  drone_simulation:
    build:
      context: .
      dockerfile: Dockerfile
      target: maker
    stdin_open: true
    tty: true
    command: >
      sh -c "make run"
    environment:
      - SIMULATION_DRONE_SPEED=5
      - SIMULATION_DRONE_PERIMETER=350
    restart: "always"
