version: "3.4"

services:
  drone_simulation:
    build:
      context: .
      dockerfile: Dockerfile
      target: maker
    stdin_open: true
    tty: true
    command: >
      sh -c "make run"
    environment:
      - CONFIG_FTP_HOST=mocks
      - CONFIG_FTP_USER=anonymous
      - CONFIG_FTP_PASSWORD=anonymous
      - CONFIG_FTP_TIMER=5
      - CONFIG_DATABASE_HOST=db
      - CONFIG_DATABASE_DBNAME=incomedb
    depends_on:
      - mocks
      - db
    restart: "always"

  db:
    image: "mongo"
    environment:
      - MONGO_INITDB_DATABASE=incomedb

  mocks:
    build:
      context: ./mocks
      dockerfile: Dockerfile
    restart: "always"
